### ISSUE TITLE
rrc_welcome error

### ISSUE THREAD

**Issue by inesariza** [compas-rrc/compas_rrc#24]
Describe in a few sentences a summary of what the problem is.

## Expected Result

welcome result, connection established

## Actual Result

```
(rrc_lab) C:\Users\arizai\Documents\Projects\algorithmic_details>C:/Users/arizai/Anaconda3/envs/rrc_lab/python.exe c:/Users/arizai/Documents/Pro
[docker_compose.txt](https://github.com/compas-rrc/compas_rrc/files/11099758/docker_compose.txt)
jects/algorithmic_details/src/algorithmic_details/waam/rrc_welcome.py
Connected.
Traceback (most recent call last):
  File "c:/Users/arizai/Documents/Projects/algorithmic_details/src/algorithmic_details/waam/rrc_welcome.py", line 9, in <module>
    abb.send_and_wait(rrc.PrintText('Welcome to COMPAS_RRC'))
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 253, in send_and_wait  
    future = self.send(instruction)
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 203, in send
    self.ensure_protocol_version()
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 146, in ensure_protocol_version
    raise Exception('Protocol version mismatch. Server={}, Client={}'.format(self._server_protocol_check['version'], CLIENT_PROTOCOL_VERSION))
Exception: Protocol version mismatch. Server=None, Client=2
```

## Reproduction Steps

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
import compas_rrc as rrc

ros = rrc.RosClient()
ros.run()

abb = rrc.AbbClient(ros, '/rob1')
print('Connected.')

abb.send_and_wait(rrc.PrintText('Welcome to COMPAS_RRC'))

ros.close()

```

## System Information

Win 10 64-bit
Python 3.8.8
compas_rrc 1.1.0
Robot C31_R31
Attached the docker_compose.yml I am running
[docker_compose.txt](https://github.com/compas-rrc/compas_rrc/files/11099819/docker_compose.txt)

the docker_compose attached here that I am running is not the same as the one [here](https://github.com/compas-rrc/compas_rrc_start/blob/main/docker/real_controller_service_port/docker-compose.yml), could this be it?

**Comment by gonzalocasas** [comment]
I think the robot has an old version of RRC, is that possible? I don't think updating the compose file to match the other one you linked will change much, on the other hand, it would be 5 minutes to test that, so perhaps give it a go.

**Comment by inesariza** [comment]
thx for the reply!

when i run the updated docker file:
the original error is gone. but I only get 'Connected.' on my side, I don't receive the message on the TP. 

other potential problems: IP address incorrect on laptop (checked, should be OK). also checked: `ping 192.168.125.1` and it works.

curious: when I run another file besides `welcome_rrc.py`, for example [this](src/algorithmic_details/waam/run_WAAM.py), I get the same? error message posted above. 

```
Traceback (most recent call last):
  File "c:/Users/arizai/Documents/Projects/algorithmic_details/src/algorithmic_details/waam/run_WAAM.py", line 186, in <module>
    feedback = experiment_call(exp_id, 'waam_column_conn', waam_column_conn_options, output_folder, waamconnection, abb)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\experiments\experiment_call.py", line 78, in experiment_call     
    feedback = fab_procedure.start(robot_client, path, fab_procedure.options)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\experiments\fab_procedure.py", line 43, in start
    feedback = func(robot_client, frames, options)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\waam\waam_column_conn.py", line 80, in waam_column_conn
    robot_client.send(SetTool('t_A036_WG1_Robacta22'))
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 203, in send
    self.ensure_protocol_version()
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 146, in ensure_protocol_version
    raise Exception('Protocol version mismatch. Server={}, Client={}'.format(self._server_protocol_check['version'], CLIENT_PROTOCOL_VERSION))
Exception: Protocol version mismatch. Server=None, Client=2
```

**Comment by gonzalocasas** [comment]
If "Connected" shows, it means the connection up to ROS is correct, but from ROS to the robot might still be failing. Could you check the logs of the rrc service in the docker desktop app and see if there's any error there?

**Comment by inesariza** [comment]
Indeed 
[docker_errors.txt](https://github.com/compas-rrc/compas_rrc/files/11100365/docker_errors.txt)

**Comment by gonzalocasas** [comment]
This is trying to connect to a robot on `192.168.125.1`, you mentioned the IP is ping-able so i assume that part is fine. (However your first compose file used a different IP address).

If the IP is correct , the something is not correct on the robot side: is RRC starting correctly when you PP to main and then Play?

**Comment by inesariza** [comment]
> (However your first compose file used a different IP address).
thank you for catching that! the new docker file is using 192.168.125.1, which is pingable, correct.

now I tried to connect to a newer project installed on the robot controller and it all works. is then the problem that the project setup is not updated on the robot controller? could you let me know @fleischp which update should i make?

thank you!

**Comment by inesariza** [comment]
great. that works for running `welcome_rrc.py`!

but I get the same error when I run my file, and I can't tell the difference:

```
Traceback (most recent call last):
  File "c:/Users/arizai/Documents/Projects/algorithmic_details/src/algorithmic_details/waam/run_WAAM.py", line 186, in <module>
    feedback = experiment_call(exp_id, 'waam_column_conn', waam_column_conn_options, output_folder, waamconnection, abb)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\experiments\experiment_call.py", line 78, in experiment_call
    feedback = fab_procedure.start(robot_client, path, fab_procedure.options)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\experiments\fab_procedure.py", line 43, in start
    feedback = func(robot_client, frames, options)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\waam\waam_column_conn.py", line 80, in waam_column_conn  
    robot_client.send(SetTool('t_A036_WG1_Robacta22'))
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 203, in send
    self.ensure_protocol_version()
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 146, in ensure_protocol_version
    raise Exception('Protocol version mismatch. Server={}, Client={}'.format(self._server_protocol_check['version'], CLIENT_PROTOCOL_VERSION))  
Exception: Protocol version mismatch. Server=None, Client=2
```

I am running these two files in the same conda environment (I understand they are calling the same version of rrc).

any ideas?

**Comment by fleischp** [comment]
Can you share the first rrc lines (creating and connecting to ROS client and ABB client) of your code? Plus your compos file for the rrc driver?

**Comment by inesariza** [comment]
My code:

```
from compas_rrc import AbbClient
from compas_rrc import Zone
from compas_fab.backends import RosClient

# Create Ros Client
ros = RosClient()
ros.run()

abb = AbbClient(ros, '/')
print('Connected')

```

> prints `Connected` correctly!

docker file attached:
[compose.txt](https://github.com/compas-rrc/compas_rrc/files/11109656/compose.txt)

**Comment by inesariza** [comment]
If I replace `from compas_fab.backends import RosClient` with `from compas_rrc import RosClient`
I see the message on the TP:  `T_CTRL -> RRC-Connected` > so that's good.

But the program stops and the error in the terminal is the same:
```
Traceback (most recent call last):
  File "c:/Users/arizai/Documents/Projects/algorithmic_details/src/algorithmic_details/waam/run_WAAM.py", line 186, in <module>
    feedback = experiment_call(exp_id, 'waam_column_conn', waam_column_conn_options, output_folder, waamconnection, abb)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\experiments\experiment_call.py", line 78, in experiment_call
    feedback = fab_procedure.start(robot_client, path, fab_procedure.options)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\experiments\fab_procedure.py", line 43, in start
    feedback = func(robot_client, frames, options)
  File "C:\Users\arizai\Documents\Projects\algorithmic_details\src\algorithmic_details\waam\waam_column_conn.py", line 80, in waam_column_conn  
    robot_client.send(SetTool('t_A036_WG1_Robacta22'))
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 203, in send
    self.ensure_protocol_version()
  File "C:\Users\arizai\Anaconda3\envs\rrc_lab\lib\site-packages\compas_rrc\client.py", line 146, in ensure_protocol_version
    raise Exception('Protocol version mismatch. Server={}, Client={}'.format(self._server_protocol_check['version'], CLIENT_PROTOCOL_VERSION))  
Exception: Protocol version mismatch. Server=None, Client=2
```

**Comment by inesariza** [comment]
OK, fixed.
I replaced:
`abb = AbbClient(ros, '/')` with `abb = AbbClient(ros, '/rob1')`
